---
linters:
  disable-all: true
  enable:
    - deadcode
    - gocyclo
    - gofmt
    - gosec
    - gosimple
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  misspell:
    locale: US
